### ISSUE TITLE
MongoError: cannot use the part (services of services.lgSSO) to traverse the element ({services: null})

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/rocketchat-lg-sso#22]
The `services` property of a user doc in the meteor mongo db might, for whatever reason, be null.

The `echo-chat` app then barfs in the course of trying to handle that user's login:

```
W20160621-23:42:37.868(-7)? (STDERR) [LG SSO] invalid or expired lgJWT token MongoError: cannot use the part (services of services.lgSSO) to traverse the element ({services: null})
W20160621-23:42:37.868(-7)? (STDERR)     at Object.Future.wait (/Users/essjay-lg/.meteor/packages/meteor-tool/.1.1.10.1crd81d++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20160621-23:42:37.868(-7)? (STDERR)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
W20160621-23:42:37.868(-7)? (STDERR)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:736:1)
W20160621-23:42:37.868(-7)? (STDERR)     at Object.CollectionHooks.defineAdvice.self (packages/matb33_collection-hooks/update.js:80:1)
W20160621-23:42:37.868(-7)? (STDERR)     at Object.collection.(anonymous function) [as update] (packages/matb33_collection-hooks/collection-hooks.js:117:1)
W20160621-23:42:37.868(-7)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:590:1)
W20160621-23:42:37.869(-7)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/dispatch_run-as-user/packages/dispatch_run-as-user.js:300:1)
W20160621-23:42:37.869(-7)? (STDERR)     at createOrUpdateUserFromJWT (server/sso.js:124:16)
W20160621-23:42:37.869(-7)? (STDERR)     at [object Object].Meteor.publish.Meteor.users.find._id (server/sso.js:145:20)
W20160621-23:42:37.869(-7)? (STDERR)     at accounts_server.js:462:32
W20160621-23:42:37.869(-7)? (STDERR)     at tryLoginMethod (accounts_server.js:239:14)
W20160621-23:42:37.869(-7)? (STDERR)     at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
W20160621-23:42:37.869(-7)? (STDERR)     at [object Object].methods.login (accounts_server.js:522:27)
W20160621-23:42:37.869(-7)? (STDERR)     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
W20160621-23:42:37.869(-7)? (STDERR)     at livedata_server.js:708:19
W20160621-23:42:37.869(-7)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20160621-23:42:37.870(-7)? (STDERR)     at livedata_server.js:706:40
W20160621-23:42:37.870(-7)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20160621-23:42:37.870(-7)? (STDERR)     at livedata_server.js:704:46
W20160621-23:42:37.870(-7)? (STDERR)     at tryCallTwo (/Users/essjay-lg/.meteor/packages/promise/.0.5.1.1cab262++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:45:5)
W20160621-23:42:37.870(-7)? (STDERR)     at doResolve (/Users/essjay-lg/.meteor/packages/promise/.0.5.1.1cab262++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:171:13)
W20160621-23:42:37.870(-7)? (STDERR)     at new Promise (/Users/essjay-lg/.meteor/packages/promise/.0.5.1.1cab262++os+web.browser+web.cordova/npm/node_modules/meteor-promise/node_modules/promise/lib/core.js:65:3)
W20160621-23:42:37.870(-7)? (STDERR)     at [object Object]._.extend.protocol_handlers.method (livedata_server.js:678:23)
W20160621-23:42:37.870(-7)? (STDERR)     at livedata_server.js:548:43
```

The culprit is here, where there's an assumption that the value of the `services` property is such that it can be traversed at all:

``` js
// server/sso.js
Meteor.users.update(rcUser, {
    $set: {
      'services.lgSSO': lgSSO
    },
  })
```

https://github.com/LearnersGuild/rocketchat-lg-sso/blob/e1522e43d69b92e6077b168d2599a025311f6e09/server/sso.js#L124-L128

**Comment by jeffreywescott** [comment]
This is related to #21, also.
